// All of these are generated by ipfs version 0.8.0 and extracted from blockstore
// ipfs block get QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH | hexdump -v -e '1/1 " %u\,"'

export const Qmdsf68UUYTSSx3i4GtDJfxzpAEZt7Mp23m3qa36LYMSiW = new Uint8Array([
  10, 4, 8, 0, 24, 0,
])

// touch tempfile && ipfs add tempfile && rm tempfile &&
export const QmbFMke1KXqnYyBBWxB74N4c5SBnJMVAiMNRcGu6x1AwQH = new Uint8Array([
  10, 4, 8, 2, 24, 0,
])

// mkdir temp && ipfs add temp -r
export const QmUNLLsPACCz1vLxQVkXqqLX5R1X345qqfHbsf67hvA3Nn = new Uint8Array([
  10, 2, 8, 1,
])

export const Qma5kEnM5fEKTXrFC5zXYRy5QG3hcMWopoFS7ijhxx19qc = new Uint8Array([
  10, 7, 8, 5, 40, 34, 48, 128, 2,
])

// ln -s hi hi.link && ipfs add hi.link
export const QmPZ1CTc5fYErTH2XXDGrfsPsHicYXtkZeVojGycwAfm3v = new Uint8Array([
  10, 6, 8, 4, 18, 2, 104, 105,
])
